#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba8) uniform writeonly image2D outputImage;

void main()
{
	uvec2 pixel = gl_GlobalInvocationID.xy;

	ivec2 imageSize = imageSize(outputImage);

	if (pixel.x >= imageSize.x || pixel.y >= imageSize.y) return;

	vec2 uv = vec2(pixel) / vec2(imageSize - 1);

	vec4 color = vec4(uv.x, uv.y, 0.0, 1.0);

	imageStore(outputImage, ivec2(pixel), color);
}