#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform PushConstants
{
	float time;
} pushConstants;

struct TestData
{
	float r;
	float g;
	float b;
};

layout(std430, binding = 1) readonly buffer TestDataBuffer
{
	TestData testData;
};

void main()
{
	uvec2 pixel = gl_GlobalInvocationID.xy;

	ivec2 imageSize = imageSize(outputImage);

	if (pixel.x >= imageSize.x || pixel.y >= imageSize.y) return;

	vec2 uv = vec2(pixel) / vec2(imageSize - 1);

	vec3 color = 0.5 * cos(pushConstants.time + uv.xyx * 6.0 + vec3(0.0, 2.0, 4.0)) + 0.5 * vec3(testData.r, testData.g, testData.b);

	imageStore(outputImage, ivec2(pixel), vec4(color, 1.0));
}