#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform PushConstants
{
	uint sphereCount;
};

struct CameraData
{
	vec4 position;
	vec4 forward;
	vec4 up;
	vec4 right;
	float planeWidth;
	float planeHeight;
};

layout(std430, binding = 1) readonly buffer CameraDataBuffer
{
	CameraData cameraInfo;
};

struct Sphere
{
	vec4 spatialData; // (x, y, z, radius)
	int materialIndex;
};

layout(std430, binding = 2) readonly buffer SphereDataBuffer
{
	Sphere spheres[];
};

struct Material
{
	vec4 albedo;
	float roughness;
	float specular;
	vec4 emission;
};

layout(std430, binding = 3) readonly buffer MaterialDataBuffer
{
	Material materials[];
};

struct Ray
{
	vec3 origin;
	vec3 direction;
};

struct IntersectPoint
{
	bool hit;
	float dist;
	vec3 position;
};

struct IntersectInfo
{
	bool hit;
	IntersectPoint point;
	Material material;
	vec3 surfaceNormal;
	vec3 lightNormal;
};

vec3 lightSourcePosition = vec3(10.0, 5.0, 20.0);

IntersectPoint CheckIntersect(Ray ray, Sphere sphere)
{
	vec3 op = ray.origin - sphere.spatialData.xyz;

	float b = 2 * dot(ray.direction, op);
	float c = dot(op, op) - sphere.spatialData.w * sphere.spatialData.w;
	float discriminant = b * b - 4 * c;

	if (discriminant < 0.0) return IntersectPoint(false, 0.0, vec3(0.0));

	float hitDist = (-b - sqrt(discriminant)) / 2.0;
	vec3 intersectPoint;
	if (hitDist > 0.0)
	{
		intersectPoint = ray.origin + hitDist * ray.direction;
	}
	else
	{
		hitDist = (-b + sqrt(discriminant)) / 2.0;
		if (hitDist <= 0.0) return IntersectPoint(false, 0.0, vec3(0.0));
		intersectPoint = ray.origin + hitDist * ray.direction;
	}

	return IntersectPoint(true, hitDist, intersectPoint);
}

vec3 Normal(vec3 point, vec3 center)
{
	return normalize(point - center);
}

IntersectInfo FindClosestIntersect(Ray ray)
{
	IntersectInfo closestIntersect = IntersectInfo(false, IntersectPoint(false, 0.0, vec3(0.0)), materials[0], vec3(0.0), vec3(0.0));
	float closestDist = 3.402823466e+38;
	for (uint s = 0; s < sphereCount; s++)
	{
		Sphere sphere = spheres[s];
		IntersectPoint intersect = CheckIntersect(ray, sphere);
		if (intersect.hit && intersect.dist < closestDist)
		{
			closestDist = intersect.dist;
			closestIntersect = IntersectInfo(true, intersect, materials[sphere.materialIndex], Normal(intersect.position, sphere.spatialData.xyz), Normal(lightSourcePosition, intersect.position));
		}
	}
	
	return closestIntersect;
}

void main()
{
	uvec2 pixel = gl_GlobalInvocationID.xy;

	ivec2 imageDims = imageSize(outputImage);

	if (pixel.x >= imageDims.x || pixel.y >= imageDims.y) return;

	vec2 pixelNorm = (vec2(pixel) + 0.5) / vec2(imageDims);
	pixelNorm = (pixelNorm - 0.5) * 2.0;
	pixelNorm.y *= -1.0;

	vec2 pixelDisplacement = vec2(pixelNorm.x * (cameraInfo.planeWidth / 2.0), pixelNorm.y * (cameraInfo.planeHeight / 2.0));
	vec3 rayDir = cameraInfo.forward.xyz + pixelDisplacement.x * cameraInfo.right.xyz + pixelDisplacement.y * cameraInfo.up.xyz;
	rayDir = normalize(rayDir);
	Ray ray = Ray(cameraInfo.position.xyz, rayDir);

	IntersectInfo intersect = FindClosestIntersect(ray);

	vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
	if (intersect.hit)
	{
		float brightness = max(dot(intersect.surfaceNormal, intersect.lightNormal), 0.0);
		color.xyz = intersect.material.albedo.xyz * brightness;
	}

	imageStore(outputImage, ivec2(pixel), color);
}