#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform PushConstants
{
	uint sphereCount;
	uint emitterCount;
	float emitterWeightSum;
	uint frameIndex;
};

struct CameraData
{
	vec4 position;
	vec4 forward;
	vec4 up;
	vec4 right;
	float planeWidth;
	float planeHeight;
};

layout(std430, binding = 1) readonly buffer CameraDataBuffer
{
	CameraData cameraInfo;
};

struct Sphere
{
	vec4 spatialData; // (x, y, z, radius)
	vec4 rotation;
	uint materialIndex;
};

layout(std430, binding = 2) readonly buffer SphereDataBuffer
{
	Sphere spheres[];
};

struct Emitter
{
	float samplingWeight;
	uint sphereIndex;
};

layout(std430, binding = 3) readonly buffer EmitterDataBuffer
{
	Emitter emitters[];
};

struct Material
{
	vec4 albedo;
	float roughness;
	float specular;
	float indexOfRefraction;
	vec4 emission;
};

layout(std430, binding = 4) readonly buffer MaterialDataBuffer
{
	Material materials[];
};

struct Ray
{
	vec3 origin;
	vec3 direction;
	vec3 accumulatedColor;
	vec3 throughput;
};

struct IntersectPoint
{
	bool hit;
	float dist;
	vec3 position;
};

struct IntersectInfo
{
	bool hit;
	float dist;
	vec3 position;
	Sphere sphere;
	uint sphereIndex;
};

struct OrthonormalBasis
{
	vec3 t;
	vec3 b;
};

struct SpecularInfo
{
	vec3 direction;
	vec3 halfVector;
};

const uint RAYS_PER_PIXEL = 10;
const uint BOUNCE_LIMIT = 4;
const uint DIRECT_LIGHT_SAMPLES = 2;
const float EPSILON = 1e-5;
const float PI = 3.14159265359;
const float RAY_JITTER_SCALE = 1.0;

uint rngState;

uint PCGHash(uint v)
{
	uint state = v * 747796405u + 2891336453u;
	uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
	return (word >> 22u) ^ word;
}

void InitRandom(uvec2 pixel, ivec2 dims, uint frameIndex)
{
	uint pixelIndex = pixel.y * uint(dims.x) + pixel.x;
	rngState = PCGHash(pixelIndex ^ PCGHash(frameIndex));
}

float Random()
{
	rngState = PCGHash(rngState);
	return float(rngState) * (1.0 / 4294967296.0);
}

float RadicalInverse_VdC(uint bits)
{
	bits = (bits << 16u) | (bits >> 16u);

	bits = ((bits & 0x55555555u) << 1u) |
		((bits & 0xAAAAAAAAu) >> 1u);

	bits = ((bits & 0x33333333u) << 2u) |
		((bits & 0xCCCCCCCCu) >> 2u);

	bits = ((bits & 0x0F0F0F0Fu) << 4u) |
		((bits & 0xF0F0F0F0u) >> 4u);

	bits = ((bits & 0x00FF00FFu) << 8u) |
		((bits & 0xFF00FF00u) >> 8u);

	return float(bits) * 2.3283064365386963e-10;
}

vec2 Hammersley2D(uint index, uint count)
{
	float u1 = (float(index) + 0.5) / float(count);
	float u2 = RadicalInverse_VdC(index);

	return vec2(u1, u2);
}

vec2 CranelyPatterson(vec2 s, vec2 offset)
{
	return fract(s + offset);
}

vec2 Sample2D(uint index, uint count)
{
	vec2 s = Hammersley2D(index, count);

	vec2 offset = vec2(Random(), Random());

	return CranelyPatterson(s, offset);
}

vec3 Normal(vec3 point, vec3 center)
{
	return normalize(point - center);
}

IntersectPoint CheckIntersect(Ray ray, Sphere sphere)
{
	vec3 op = ray.origin - sphere.spatialData.xyz;

	float b = 2 * dot(ray.direction, op);
	float c = dot(op, op) - sphere.spatialData.w * sphere.spatialData.w;
	float discriminant = b * b - 4 * c;

	if (discriminant < 0.0) return IntersectPoint(false, 0.0, vec3(0.0));

	float hitDist = (-b - sqrt(discriminant)) / 2.0;
	vec3 intersectPoint;
	if (hitDist > 0.0)
	{
		intersectPoint = ray.origin + hitDist * ray.direction;
	}
	else
	{
		hitDist = (-b + sqrt(discriminant)) / 2.0;
		if (hitDist <= 0.0) return IntersectPoint(false, 0.0, vec3(0.0));
		intersectPoint = ray.origin + hitDist * ray.direction;
	}

	return IntersectPoint(true, hitDist, intersectPoint);
}

IntersectInfo FindClosestIntersect(Ray ray)
{
	IntersectInfo closestIntersect = IntersectInfo(false, 3.402823466e+38, vec3(0.0), spheres[0], 0);
	for (uint s = 0; s < sphereCount; s++)
	{
		Sphere sphere = spheres[s];
		IntersectPoint intersect = CheckIntersect(ray, sphere);
		if (intersect.hit && intersect.dist < closestIntersect.dist)
		{
			closestIntersect = IntersectInfo(true, intersect.dist, intersect.position, sphere, s);
		}
	}
	
	return closestIntersect;
}

bool IsVisible(vec3 origin, vec3 direction, float maxDistance, uint emitterIndex, uint originIndex)
{
	Ray ray = Ray(origin, direction, vec3(0.0), vec3(1.0));

	for (uint s = 0; s < sphereCount; s++)
	{
		if (s == emitterIndex || s == originIndex) continue;

		IntersectPoint intersect = CheckIntersect(ray, spheres[s]);

		if (intersect.hit && intersect.dist < maxDistance) return false;
	}

	return true;
}

OrthonormalBasis CalculateOrthonormalBasis(vec3 normal)
{
	vec3 a;
	if (abs(normal.z) < 0.99)
	{
		a = vec3(0.0, 0.0, 1.0);
	}
	else
	{
		a = vec3(1.0, 0.0, 0.0);
	}

	vec3 t = normalize(cross(a, normal));
	vec3 b = cross(normal, t);

	return OrthonormalBasis(t, b);
}

SpecularInfo SpecularDir(vec3 rayDir, vec3 normal, float roughness, uint sampleIndex)
{
	float a = roughness * roughness;

	vec2 samp = Sample2D(sampleIndex, RAYS_PER_PIXEL);

	float azimuth = 2.0 * PI * samp.x;

	float tanSquareTheta = a * a * samp.y / (1.0 - samp.y);
	float cosTheta = 1.0 / sqrt(1.0 + tanSquareTheta);
	float sinTheta = sqrt(1.0 - cosTheta * cosTheta);

	OrthonormalBasis basis = CalculateOrthonormalBasis(normal);

	vec3 h = sinTheta * cos(azimuth) * basis.t + sinTheta * sin(azimuth) * basis.b + cosTheta * normal;

	vec3 specularDir = rayDir - 2.0 * dot(rayDir, h) * h;
	
	return SpecularInfo(specularDir, h);
}

vec3 DiffuseDir(vec3 normal, uint sampleIndex)
{
	vec2 samp = Sample2D(sampleIndex, RAYS_PER_PIXEL);

	float r = sqrt(samp.x);
	float angle = 2.0 * PI * samp.y;

	float x = r * cos(angle);
	float y = r * sin(angle);
	float z = sqrt(1.0 - x * x - y * y);

	OrthonormalBasis basis = CalculateOrthonormalBasis(normal);

	vec3 diffuseDir = x * basis.t + y * basis.b + z * normal;

	return diffuseDir;
}

uint SampleEmitter(out float selectionPdf)
{
	float emitterSample = Random() * emitterWeightSum;
	float accumulated = 0.0;

	for (uint i = 0; i < emitterCount; i++)
	{
		accumulated += emitters[i].samplingWeight;

		if (emitterSample < accumulated)
		{
			selectionPdf = emitters[i].samplingWeight / emitterWeightSum;
			return emitters[i].sphereIndex;
		}
	}

	uint last = emitterCount - 1;
	selectionPdf = emitters[last].samplingWeight / emitterWeightSum;
	return emitters[last].sphereIndex;
}

Ray TraceRay(Ray ray, uint rayIndex)
{
	if (sphereCount < 1) return ray;

	for (uint b = 0; b < BOUNCE_LIMIT; b++)
	{
		IntersectInfo intersect = FindClosestIntersect(ray);

		if (!intersect.hit) return ray;

		uint sampleIndex = rayIndex;

		Sphere sphere = intersect.sphere;
		vec3 spherePosition = sphere.spatialData.xyz;
		Material material = materials[sphere.materialIndex];
		vec3 albedo = material.albedo.xyz;
		vec3 emission = material.emission.xyz;

		vec3 surfaceNormal = Normal(intersect.position, spherePosition);

		ray.accumulatedColor += ray.throughput * material.emission.xyz;

		vec3 directLight = vec3(0.0);
		for (uint s = 0; s < DIRECT_LIGHT_SAMPLES; s++)
		{
			if (emitterCount > 0 && emitterWeightSum > 0.0)
			{
				float selectionPdf;
				uint emitterIndex = SampleEmitter(selectionPdf);
				Sphere emitter = spheres[emitterIndex];
				Material emitterMaterial = materials[emitter.materialIndex];

				vec3 x = intersect.position;
				vec3 c = emitter.spatialData.xyz;
				float r = emitter.spatialData.w;

				vec3 toCenter = c - x;
				float shadowDist = length(toCenter);
				vec3 centerDirection = toCenter / shadowDist;

				if (shadowDist > r)
				{
					float sinThetaMax = r / shadowDist;
					float cosThetaMax = sqrt(1.0 - sinThetaMax * sinThetaMax);

					float oneMinusCosThetaMax = (sinThetaMax * sinThetaMax) / (1.0 + cosThetaMax);
					float conditionalPdf = 1.0 / (2.0 * PI * oneMinusCosThetaMax);
					float completePdf = selectionPdf * conditionalPdf;

					uint sx = s % 4u;
					uint sy = s / 4u;

					float u1 = (float(sx) + Random()) / 4.0;
					float u2 = (float(sy) + Random()) / 2.0;

					float cosTheta = 1.0 - u1 * (1.0 - cosThetaMax);
					float sinTheta = sqrt(max(0.0, 1.0 - cosTheta * cosTheta));
					float phi = 2.0 * PI * u2;

					OrthonormalBasis basis = CalculateOrthonormalBasis(centerDirection);

					vec3 lightDirection = sinTheta * cos(phi) * basis.t +
						sinTheta * sin(phi) * basis.b + cosTheta * centerDirection;

					vec3 origin = x + EPSILON * surfaceNormal;

					Ray shadowRay = Ray(origin, lightDirection, vec3(0.0), vec3(1.0));

					IntersectPoint emitterIntersect = CheckIntersect(shadowRay, emitter);

					if (emitterIntersect.hit && IsVisible(origin, lightDirection, emitterIntersect.dist, emitterIndex, intersect.sphereIndex))
					{
						float nDotLight = max(dot(surfaceNormal, lightDirection), 0.0);

						directLight += emitterMaterial.emission.xyz * (albedo / PI) * nDotLight / completePdf;
					}
				}
			}
		}

		if (DIRECT_LIGHT_SAMPLES > 0)
		{
			directLight /= float(DIRECT_LIGHT_SAMPLES);
		}

		ray.accumulatedColor += ray.throughput * directLight;

		float lobeSample = (float(rayIndex) + Random()) / float(RAYS_PER_PIXEL);

		if (lobeSample < material.specular)
		{
			vec3 incomingDir = -ray.direction;

			SpecularInfo specular = SpecularDir(ray.direction, surfaceNormal, material.roughness, sampleIndex);
			ray.direction = specular.direction;

			float nDotIncoming = max(dot(surfaceNormal, incomingDir), 0.0);
			float nDotOutgoing = max(dot(surfaceNormal, specular.direction), 0.0);

			if (nDotIncoming <= 0.0 || nDotOutgoing <= 0.0)
			{
				ray.throughput = vec3(0.0);
				break;
			}
			else
			{
				float nDotH = max(dot(surfaceNormal, specular.halfVector), 0.0);
				float outgoingDotH = abs(dot(specular.direction, specular.halfVector));
				float incomingDotH = max(dot(incomingDir, specular.halfVector), 0.0);

				float f0 = (1.0 - material.indexOfRefraction) / (1.0 + material.indexOfRefraction);
				f0 *= f0;

				float f = f0 + (1.0 - f0) * pow((1.0 - incomingDotH), 5);

				float k = material.roughness + 1.0;
				k = k * k / 8.0;

				float gIncoming = nDotIncoming / (nDotIncoming * (1.0 - k) + k);
				float gOutgoing = nDotOutgoing / (nDotOutgoing * (1.0 - k) + k);

				float g = gIncoming * gOutgoing;

				float numerator = f * g * outgoingDotH;
				float denominator = material.specular * nDotIncoming * nDotH;

				ray.throughput *= numerator / denominator;
			}
		}
		else
		{
			ray.direction = DiffuseDir(surfaceNormal, sampleIndex);
			ray.throughput *= albedo / (1.0 - material.specular);
		}

		ray.origin = intersect.position + EPSILON * surfaceNormal;
	}

	return ray;
}

vec3 ToneMap(vec3 color)
{
	return color / (1.0 + color);
}

void main()
{
	const uvec2 pixel = gl_GlobalInvocationID.xy;

	const ivec2 imageDims = imageSize(outputImage);

	if (pixel.x >= imageDims.x || pixel.y >= imageDims.y) return;

	InitRandom(pixel, imageDims, frameIndex);

	vec2 pixelNorm = (vec2(pixel) + 0.5) / vec2(imageDims);
	pixelNorm = (pixelNorm - 0.5) * 2.0;
	pixelNorm.y *= -1.0;

	const vec2 pixelDims = vec2(cameraInfo.planeWidth / imageDims.x, cameraInfo.planeHeight / imageDims.y);

	const vec3 cameraPosition = cameraInfo.position.xyz;

	const vec2 pixelDisplacement = vec2(pixelNorm.x * (cameraInfo.planeWidth / 2.0), pixelNorm.y * (cameraInfo.planeHeight / 2.0));

	vec3 averageColor = vec3(0.0);
	for (uint r = 0; r < RAYS_PER_PIXEL; r++)
	{
		vec2 samp = Sample2D(r, RAYS_PER_PIXEL);

		vec2 rayOffset = RAY_JITTER_SCALE * (samp - 0.5);
		vec2 rayPixelDisplacement = pixelDisplacement + rayOffset * pixelDims;

		vec3 rayDir = cameraInfo.forward.xyz + rayPixelDisplacement.x * cameraInfo.right.xyz + rayPixelDisplacement.y * cameraInfo.up.xyz;
		rayDir = normalize(rayDir);
		Ray ray = Ray(cameraPosition, rayDir, vec3(0.0), vec3(1.0));
		averageColor += TraceRay(ray, r).accumulatedColor;
	}
	averageColor /= float(RAYS_PER_PIXEL);

	averageColor = ToneMap(averageColor);

	imageStore(outputImage, ivec2(pixel), vec4(averageColor, 1.0));
}