#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba16f) uniform readonly image2D hdrImage;
layout(binding = 1, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform PushConstants
{
	float exposure;
	bool correctGamma;
};

vec3 ApplyExposure(vec3 color)
{
	return 1.0 - exp(-color * exposure);
}

vec3 CorrectGamma(vec3 color)
{
	return pow(color, vec3(1.0 / 2.2));
}

void main()
{
	const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

	const ivec2 imageDims = imageSize(outputImage);

	if (pixel.x >= imageDims.x || pixel.y >= imageDims.y) return;

	vec4 pixelColor = imageLoad(hdrImage, pixel);

	pixelColor.rgb = ApplyExposure(pixelColor.rgb);
	if (correctGamma) pixelColor.rgb = CorrectGamma(pixelColor.rgb);

	imageStore(outputImage, pixel, pixelColor);
}